o: linux
language: java
install: true
jdk: openjdk8
script:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
  gradle publish; else gradle bake publish; fi
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - secure: qH8jpATl/XBfDdeAoALLgGNXeA/WnGVbixMWr55ejDOXY2vehkPBNcCtfJrumfpo6KphPyE45vkacNER3Wegpm8aVZBPgGNAx61izr8Q3vLqRkd2021rU1vIUsrQ2U8FpDL9SHwDDzedKA9x/M5+4Zw+/e8q20l6nXA2CGp0Ft3EXMjikCdPtJbN7RFDBW74SWaHhVJYWMV3A9e3/553wDykRFzbzQlDMJLbb6DjHcKJptFiXuQNRmeAe+LBj48qR4BTqd6EkRv986LKXDtdzOhBDaVVIusuXsDfnwT4Lbi2l+B5tQSB/webQgah2N/614j7RVTMPB1yZLP3S4Qw0prKqIxuEQ0Jrnwb9j277r4xIsTsnxIXiibBAzrtE0/4U2W2DLgodQdwLOIh8ROcdxZAoENV4el2//tj7UBwmPg/zz51e8LdVtAj8MO4q32ZUbQRf5fF0c0se0Q7h2Wn2CkLNufHuBwJvLrCWRA8OsiRGjZPmEWKqVNg8bP//fwUaD/r6g5uk2duW/Q3REzYvV06Acjds3m1GPFOj35WlGatBoYSRzqhHGlIwy773PMz2Y/OHCabS+65yAzczUj+d9RAz+aa0Rb0ZfG6AROnP9dt0hh3hp5SO+6GwAOq9xOpT1PH5cZgyPqwBB2hnYrjFeNl4Oumf/dzqErrKaQrW2w=
